{{- if eq .Values.s3.mode "deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fakes3pp.fullnameS3" . }}
  labels:
    {{- include "fakes3pp.labelsS3" . | nindent 4 }}
spec:
  {{- if not .Values.s3.autoscaling.enabled }}
  replicas: {{ .Values.s3.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fakes3pp.selectorLabelsS3" . | nindent 6 }}
  strategy:
    {{- if eq .Values.s3.rollout.strategy "RollingUpdate" }}
    {{- with .Values.s3.rollout.rollingUpdate }}
    rollingUpdate:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
    type: {{ .Values.s3.rollout.strategy }}
  template:
    metadata:
      {{- with .Values.s3.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fakes3pp.labelsS3" . | nindent 8 }}
        {{- with .Values.s3.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.s3.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fakes3pp.serviceAccountNameS3" . }}
      securityContext:
        {{- toYaml .Values.s3.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.s3.securityContext | nindent 12 }}
          image: "{{ .Values.shared.image.repository }}:{{ .Values.shared.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.shared.image.pullPolicy }}
          command: ["/fakes3pp", "proxys3", "--dot-env", "skip"]
          ports:
          {{- if and (eq (int .Values.s3.service.port) (int 0)) (eq (int .Values.s3.service.portTLS) (int 0)) }}
             {{ fail "One must at least have 1 s3 service port <> 0" }}
          {{- end}}
          {{- if not (eq (int .Values.s3.service.port) (int 0)) }}
            - name: http
              containerPort: {{ .Values.s3.service.port }}
              protocol: TCP
          {{- end }}
          {{- if not (eq ( int .Values.s3.service.portTLS) (int 0)) }}
            - name: tls
              containerPort: {{ .Values.s3.service.portTLS }}
              protocol: TCP
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.s3.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.s3.readinessProbe | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "fakes3pp.name" . }}
            {{- with .Values.s3.envFrom }}
            {{- toYaml .Values.s3.envFrom | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.s3.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.s3.defaultVolumeMounts }}
            {{- if not (eq ( int .Values.s3.service.portTLS) (int 0)) }}
          - name: tls
            mountPath: "{{ .Values.s3.config.tlsDir }}"
            readOnly: true
            {{- end }}
          - name: jwt
            mountPath: "{{ .Values.shared.config.jwt.dir }}"
            readOnly: true
          - name: policies
            mountPath: "{{ .Values.shared.config.policies.dir }}"
            readOnly: true
          - name: backend-cfg
            mountPath: "{{ .Values.s3.config.backends.dir }}"
            readOnly: true
          {{- else }}
            {{- if not .Values.s3.extraVolumeMounts }}
              {{ fail "If you disable s3.defaultVolumeMounts you must provide s3.extraVolumeMounts" }}
            {{- end}}
          {{- end}}
          {{- with .Values.s3.extraVolumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      volumes:
        {{- if .Values.s3.defaultVolumes }}
          {{- if not (eq ( int .Values.s3.service.portTLS) (int 0)) }}
        - name: tls
          secret:
            secretName: {{ .Values.s3.service.fqdn }}-cert
            optional: false
          {{- end }}
        - name: jwt
          secret:
            secretName: {{ .Values.shared.config.jwt.secretName }}
            optional: false
        - name: policies
          secret:
            secretName: {{ .Values.shared.config.policies.secretName }}
            optional: false
        - name: backend-cfg
          secret:
            secretName: {{ .Values.s3.config.backends.secretName }}
            optional: false
        {{- else }}
          {{- if not .Values.s3.extraVolumes }}
            {{ fail "If you disable s3.defaultVolumes you must provide s3.extraVolumes" }}
          {{- end}}
        {{- end}}
        {{- with .Values.s3.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.s3.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.s3.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.s3.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
