{{- if .Values.sts.ingress.enabled -}}
{{- $fullName := include "fakes3pp.fullnameSTS" . -}}
{{- $svcPort := .Values.sts.service.port -}}
{{- if and .Values.sts.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.sts.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.sts.ingress.annotations "kubernetes.io/ingress.class" .Values.sts.ingress.className}}
  {{- end }}
{{- end }}
{{- $svcName := ternary (printf "%s-%s" $fullName "headless") $fullName .Values.sts.service.headless}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "fakes3pp.labelsSTS" . | nindent 4 }}
  annotations:
    {{- if .Values.sts.ingress.cnameTarget }}
    external-dns.alpha.kubernetes.io/target: {{ .Values.sts.ingress.cnameTarget }}
    {{- else }}
    github.com/VITObelgium/fakes3pp: just-a-hack-to-always-have-at-least-1-annotation
    {{- end}}
    {{- with .Values.sts.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end}}
spec:
  {{- if and .Values.sts.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.sts.ingress.className }}
  {{- end }}
  {{- if .Values.sts.ingress.tls }}
  tls:
    {{- range .Values.sts.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.sts.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $svcName}}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $svcName}}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
