{{- with .Values.shared.config.jwt }}
  {{- if .data }}
kind: Secret
apiVersion: v1
metadata:
  name: "{{ .secretName }}"
stringData:
  jwt_rsa: |
{{ .data.jwt_rsa | indent 4 }}
  jwt_rsa.pub: |
{{ .data.jwt_rsa_pub | indent 4 }}
type: Opaque
  {{- end}}
{{- end}}
