{{- with .Values.shared.config.policies }}
  {{- if .documents }}
kind: Secret
apiVersion: v1
metadata:
  name: "{{ .secretName }}"
data:
  {{- range .documents }}
  {{ .arn | b32enc | replace "=" "8" | replace "\n" "" }}.json.tmpl: {{ .content | toJson | b64enc }}
  {{- end}}

  {{- end}}
{{- end}}
