{{- if .Values.sts.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fakes3pp.serviceAccountNameSTS" . }}
  labels:
    {{- include "fakes3pp.labelsSTS" . | nindent 4 }}
  {{- with .Values.sts.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.sts.serviceAccount.automount }}
{{- end }}
