{{- if .Values.s3.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fakes3pp.serviceAccountNameS3" . }}
  labels:
    {{- include "fakes3pp.labelsS3" . | nindent 4 }}
  {{- with .Values.s3.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.s3.serviceAccount.automount }}
{{- end }}
