# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: LocalVIP

on:
  push:
    branches: [ "*", "**" ]
    paths:
      - localvip/**
  pull_request:
    branches: [ "*", "**" ]
    paths:
      - localvip/**

env:
  LOCALVIP_IMAGE_NAME: fakes3pp-localvip

jobs:
  # This pushes the image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build init image
        run: docker build ./localvip --file localvip/Dockerfile --tag $LOCALVIP_IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        if: github.repository_owner != 'VITObelgium'
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$LOCALVIP_IMAGE_NAME

          # This changes all uppercase characters to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # This strips the git ref prefix from the version.
          VERSION=$(echo "${{ github.sha }}")
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $LOCALVIP_IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
